language: ruby
sudo: false 
rvm:
- 2.3.3

script: ./scripts/cibuild.sh # build packages using jekyll

branches:
  only:
  - source     # deploy from sources branch only

deploy:
  skip_cleanup: true
  provider: script 
  script: scripts/deploy.sh #deploy to gh pages repository
  on:
          branch: source

notifications:
  email:
    recipients:
      - samsel@dbis.rwth-aachen.de 
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - ENCRYPTION_LABEL: "16f9db21fba8"
  - COMMIT_AUTHOR_EMAIL: "samsel@dbis.rwth-aachen.de"
