language: ruby
sudo: false 
rvm:
- 2.3.3

script: ./scripts/cibuild.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
  - source     # deploy from sources branch only

deploy:
  skip_cleanup: true
  provider: script 
  script: scripts/deploy.sh
  on:
          branch: source


env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - ENCRYPTION_LABEL: "16f9db21fba8"
  - COMMIT_AUTHOR_EMAIL: "samsel@dbis.rwth-aachen.de"
